import Vector from '../images/backarrow/Vector.png'
import eye from '../images/eye/Group.png'
import fb from '../images/fb/Vector.png'
import apple from '../images/apple/cib_apple.png'
import google from '../images/google/google.png'
import menu from '../images/menu/menu.png'
import location from '../images/location/Frame.png'
import message from '../images/message/message.png'
import search from '../images/search/search.png'
import plus from '../images/plus/Frame.png'
import profileicon from '../images/profileicon/profileicon.png'
import more from '../images/more/more.png'
import rectangle from '../images/rectangle/rectangle.png'
import homefocussed from '../images/homefocussed/homefocussed.png'
import home from '../images/home/home.png'
import profilefocussed from '../images/profilefocussed/profilefocussed.png'
import heart from '../images/heart/heart.png'
import cart from '../images/cart/cart.png'

export { Vector, eye, fb, apple, google, menu, location, message, search, plus, profileicon, more, rectangle, homefocussed, home, profilefocussed, heart, cart }